### ISSUE TITLE
Chapter 17 - Exercise 4

### ISSUE THREAD

**Issue by fdrmrc** [bewuethr/stroustrup-ppp#14]
Dear @bewuethr 

running the executable (after compiling with `-std=c++11` or `-std=c++14`) a `pointer being freed was not allocated` error is obtained, coming from 

https://github.com/bewuethr/stroustrup-ppp/blob/fe98f3c9edd651d1c3f8528db45b54b6f6cb1a7a/chapter17/chapter17_ex04.cpp#L22

Best,
Marco

**Comment by bewuethr** [comment]
I wrote this with a pre-C++-11 compiler, does the problem go away with `-std=c++98`?

**Comment by fdrmrc** [comment]
No, it doesn't. The issue stems from the fact that we cannot call `delete[]` on `s`, as it has not been allocated with `new`. Also, the destructor of `std::string` already cleans up the memory when the object goes out of scope. If you remove that line, it runs just fine, with no memory leaks

**Comment by bewuethr** [comment]
Ah, great, I'll update later today!

**Comment by fdrmrc** [comment]
Thanks :-)
