### ISSUE TITLE
this will never happen

### ISSUE THREAD

**Issue by ihavesomepoblem** [bewuethr/stroustrup-ppp#7]
https://github.com/bewuethr/stroustrup_ppp/blob/b47ff8759174cf3aa8365d47bd61c3b4c06f8316/chapter18/chapter18_ex01.cpp#L50

fix 
add: `if (*(s1+i+1)==0 && *(s2+i+1) == 0) return 0;` for handling identical words
change first condition to: `if (*(s1+i+1)==0 && *(s2+i) || *(s1+i) < *(s2+i)) return -1;`

**Comment by bewuethr** [comment]
It won't exactly never happen, for example input `aaa bbb` correctly outputs `aaa < bbb`.

However, `aa aaa` is incorrectly identified as equal. The idea, if I remember correctly, was to test for inequality, and if that falls through, return `0` for equal. I'll update.

**Comment by ihavesomepoblem** [comment]
Yes, you're right, I just confused the associativity of operators && and ||
